[package]
name = "unnamed-voxel-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
bevy-inspector-egui = "0.19.0"
bevy_flycam = "0.10.1"
bracket-noise = "0.8.7"
rand = "0.8.5"
